In [1]:
import numpy as np
def init_pop(pop_size):
    return np.random.randint(8,size=(pop_size,8))

In [2]:
def calc_fitness(population):
    fitness_vals=[]
    for x in population:
        penalty=0
        for i in range(8):
            r=x[i]
            for j in range(8):
                if i==j:
                    continue
                d=abs(i-j)
                if x[j] in [r,r-d,r+d]:
                    penalty+=1
        fitness_vals.append(penalty)
    return -1*np.array(fitness_vals)

In [3]:
def selection(population,fitness_vals):
    probs=fitness_vals.copy()
    probs+=abs(probs.min())+1
    probs=probs/probs.sum()
    N=len(population)
    indices=np.arange(N)
    selected_indices=np.random.choice(indices,size=N,p=probs)
    selected_pop=population[selected_indices]
    return selected_pop

In [4]:
def crossover(parent1,parent2,pc):
    r=np.random.random()
    if r<pc:
        m=np.random.randint(1,8)
        child1=np.concatenate([parent1[:m],parent2[m:]])
        child2=np.concatenate([parent2[:m],parent1[m:]])
    else:    
        child1=parent1.copy()
        child2=parent2.copy()
    return child1,child2

In [5]:
def mutation(individual,pm):
    r=np.random.random()
    if r<pm:
        m=np.random.randint(8)
        individual[m]=np.random.randint(8)
    return individual

In [6]:
def crossover_mutation(selected_pop,pc,pm):
    N=len(selected_pop)
    new_pop=np.empty((N,8),dtype=int)
    for i in range(0,N,2):
        parent1=selected_pop[i]
        parent2=selected_pop[i+1]
        child1,child2=crossover(parent1,parent2,pc)
        new_pop[i]=child1
        new_pop[i+1]=child2
    for i in range(N):
        mutation(new_pop[i],pm)
    return new_pop

In [7]:
def eight_queens(pop_size,max_generations,pc=0.7,pm=0.01):
    population=init_pop(pop_size)
    best_fitness_overall=None
    for i_gen in range(max_generations):
        fitness_vals=calc_fitness(population)
        best_i=fitness_vals.argmax()
        best_fitness=fitness_vals[best_i]
        if best_fitness_overall is None or best_fitness>best_fitness_overall:
            best_fitness_overall=best_fitness
            best_solution=population[best_i]
        if best_fitness==0:
            print('\n found optimal solution')
            break
        selected_pop=selection(population,fitness_vals)
        population=crossover_mutation(selected_pop,pc,pm)
    print(best_solution)
        

In [8]:
initial_population=init_pop(4)
print(initial_population)

[[4 5 7 5 1 5 1 1]
 [2 4 5 3 6 4 0 0]
 [1 2 2 3 3 0 3 7]
 [2 7 4 7 7 5 5 6]]


In [9]:
fitness_vals=calc_fitness(initial_population)
print(fitness_vals)

[-16 -12 -16 -16]


In [10]:
selected_pop=selection(initial_population,fitness_vals)
print(selected_pop)

[[2 4 5 3 6 4 0 0]
 [2 4 5 3 6 4 0 0]
 [2 4 5 3 6 4 0 0]
 [4 5 7 5 1 5 1 1]]


In [11]:
parent1=selected_pop[0]
parent2=selected_pop[1]
child1,child2=crossover(parent1, parent2, pc=0.7)
print(parent1,'-->',child1)
print(parent2,'-->',child2)

[2 4 5 3 6 4 0 0] --> [2 4 5 3 6 4 0 0]
[2 4 5 3 6 4 0 0] --> [2 4 5 3 6 4 0 0]


In [12]:
eight_queens(pop_size=100,max_generations=10000,pc=0.5,pm=0.05)


 found optimal solution
[5 2 0 6 4 7 1 3]
